[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false

[window.padding]
x = 15
y = 10

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Semibold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Semibold"

# Default colors
[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#C7B8B8'
green   = '#B9C1B6'
yellow  = '#CECEB5'
blue    = '#C1C4CE'
magenta = '#D5BEBE'
cyan    = '#B4D0D7'
white   = '#FFFFFF'

# Bright colors
[colors.bright]
black   = '#383838'
red     = '#DBD1D1'
green   = '#D3D8D1'
yellow  = '#E0E0D0'
blue    = '#D7D9DF'
magenta = '#E4D6D6'
cyan    = '#CEE0E5'
white   = '#FFFFFF'
